### ISSUE TITLE
Build fails - Ubuntu 15.10, Node v0.12.10, npm 2.14.9

### ISSUE THREAD

**Issue by mon** [audiocogs/ogg.js#8]
I'm having issues with aurora+ogg.js+vorbis.js in a Web Worker, so I'm attempting to build from source to see if a newer Browserify version makes everything mesh nicely.

This is a brand new Ubuntu Server 15.10 inside a VM, so it's safe to assume there are no conflicts from my existing environment.

The first issue was the arguments to `sed` being incorrect inside `compileOgg.sh`. I imagine an update changed the syntax. I had to change `sed -i '' 's/-O20/-O2/g' configure` to `sed -i 's/-O20/-O2/g' configure`. Note the missing empty string as the second argument.

There are several errors, so I've attached a log. I'm not sure if they're related or simply a cascade from the first error.
[install.txt](https://github.com/audiocogs/ogg.js/files/127824/install.txt)

**Comment by mon** [comment]
The modifications to the `sed` line are still required, but following emscripten's install instructions instead of blindly apt-getting made the build succeed.

**Comment by fasterthanlime** [comment]
@mon The first sed syntax you mention looks like BSD sed (Mac/OSX), the second looks like GNU sed.

**Comment by mon** [comment]
Never considered that, thanks for the heads up @fasterthanlime

**Comment by fasterthanlime** [comment]
sed is always annoying to write cross-platform tidbits for, I'd recommend using another utility :( shame that the BSD/GNU schism exists.
